server:
  port: 9090

spring:
  application:
    name: api-gateway-zacamil
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      server:
        webmvc:
          routes:
            - id: ruta-alta-medica
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/altas/**
            - id: ruta-limpieza
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/limpieza/**
            - id: ruta-consultas-camas
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/consultas/**