spring.application.name=alta-medica-servic
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ZacamilDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Zacamil_Strong_Pass_2026!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true