spring.application.name=alta-medica-servic
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ZacamilDB;encrypt=false
spring.datasource.username=sa
spring.datasource.password=Zacamil_Strong_Pass_2026!

# --- CONFIGURACIÓN DE BASE DE DATOS ---
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# --- CONFIGURACIÓN DE SPRING CLOUD STREAM (NUEVA SINTAXIS) ---
spring.cloud.stream.bindings.enviarAlta-out-0.destination=altas-topic

# Le decimos a Spring explícitamente que es un Topic (¡Esta es la línea que faltaba!)
spring.cloud.stream.servicebus.bindings.enviarAlta-out-0.producer.entity-type=topic

# Credenciales directas
spring.cloud.stream.servicebus.bindings.enviarAlta-out-0.producer.connection-string=Endpoint=sb://bus-zacamil-std.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=${AZURE_SB_KEY}