server:
  port: 8083

spring:
  application:
    name: consultas-cama-service
  cloud:
    function:
      # 1. AQUI AGREGAMOS EL NUEVO EVENTO AL FINAL
      definition: procesarAltaMedica;procesarCamaLimpia;procesarIngresoPaciente
    azure:
      cosmos:
        endpoint: ${COSMOS_ENDPOINT:https://localhost:8081}
        key: ${COSMOS_KEY}
        database: ZacamilReadDB
        populate-query-metrics: true
      servicebus:
        connection-string: Endpoint=sb://buss-zacamil-std.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=${AZURE_SB_KEY}
    stream:
      bindings:
        procesarAltaMedica-in-0:
          destination: altas-topic
          group: consultas-sub
        procesarCamaLimpia-in-0:
          destination: camas-disponibles-topic
          group: consultas-sub
        # 2. NUEVO BINDING DE ENTRADA PARA EL INGRESO
        procesarIngresoPaciente-in-0:
          destination: ingresos-topic
          group: consultas-sub
        # 3. NUEVO BINDING DE SALIDA (Para que el StreamBridge no de error 400)
        ingresos-topic-out-0:
          destination: ingresos-topic
      servicebus:
        bindings:
          procesarAltaMedica-in-0:
            consumer:
              auto-complete: true
          procesarCamaLimpia-in-0:
            consumer:
              auto-complete: true
          # 4. AUTO-COMPLETE PARA EL NUEVO EVENTO
          procesarIngresoPaciente-in-0:
            consumer:
              auto-complete: true
          ingresos-topic-out-0:
            producer:
              entity-type: topic