spring.application.name=servicio-limpieza
server.port=8082

# Conexi\u00f3n a la Base de Datos SQL Server (ZacamilDB)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ZacamilDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Zacamil_Strong_Pass_2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Azure Service Bus Configuration
# Reemplace <namespace> y <key> con los valores reales
# Azure Service Bus Configuration
spring.cloud.azure.servicebus.connection-string=Endpoint=sb://bus-zacamil-std.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=${AZURE_SB_KEY}

# Spring Cloud Stream Configuration
spring.cloud.function.definition=recibirAlta
spring.cloud.stream.bindings.recibirAlta-in-0.destination=altas-topic
spring.cloud.stream.bindings.recibirAlta-in-0.group=limpieza-sub
