spring.application.name=servicio-limpieza
server.port=8082

# Conexion a la Base de Datos SQL Server (ZacamilDB)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=ZacamilDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Zacamil_Strong_Pass_2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Azure Service Bus Configuration (Para RECIBIR de la Epica 3)
spring.cloud.azure.servicebus.connection-string=Endpoint=sb://buss-zacamil-std.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=${AZURE_SB_KEY}
spring.cloud.function.definition=recibirAlta
spring.cloud.stream.bindings.recibirAlta-in-0.destination=altas-topic
spring.cloud.stream.bindings.recibirAlta-in-0.group=limpieza-sub

# NUEVO: Configuracion para ENVIAR el evento CamaDisponible (Epica 4)
spring.cloud.stream.bindings.enviarCamaLimpia-out-0.destination=camas-disponibles-topic
spring.cloud.stream.servicebus.bindings.enviarCamaLimpia-out-0.producer.entity-type=topic
spring.cloud.stream.servicebus.bindings.enviarCamaLimpia-out-0.producer.connection-string=Endpoint=sb://buss-zacamil-std.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=${AZURE_SB_KEY}